In [11]:
import numpy
n = numpy.arange(27)
print(type(n))
print(n)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [12]:
n = n.reshape(3,3,3)
n

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [15]:
import cv2
import os
os.getcwd()

'D:\\ModernLab\\Learning\\Python\\App2_MySql'

In [27]:
im_g = cv2.imread(os.getcwd() + "\\InputFiles\\smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [28]:
cv2.imwrite(os.getcwd() + "\\InputFiles\\smallgray1.png", im_g)

True

In [29]:
im_g + 1

array([[188, 159, 105, 122, 144],
       [199, 126,   0,   0, 148],
       [210, 135,   0,  98, 183]], dtype=uint8)

In [33]:
print(numpy.vstack((im_g, im_g+1, im_g+2)))

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [188 159 105 122 144]
 [199 126   0   0 148]
 [210 135   0  98 183]
 [189 160 106 123 145]
 [200 127   1   1 149]
 [211 136   1  99 184]]
